Readme dla zadanie 1 z laboratorium z zaawansowanych metod programistycznych

w trakcie wykonywanie zadania w miejscu rozwiązywania konfliktów , połączyłem tak , że była funkcja cout bez std i bez using namespace std;
5

zmiana

podczas testu pull popełniłem kolejny błąd z tym , że zrobiłem pull po zmianach lokalnych i commicie , próbując zrobić push miałem konflikt , musiałem jeszcze raz robić resolve w meld , jest to w logu 
